on:
  pull_request:
    branches:
      - main

name: Test One

jobs:
  check-github-actions:
    name: Check GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for affected paths
        id: changes
        uses: dorny/paths-filter@v2.11.1
        with:
          filters: |
            github-actions:
              - '.github/*/**/*.{yaml,yml}'
